---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

if(!"collapsibleTree" %in% installed.packages()) { install.packages("collapsibleTree") };
if(!"data.tree"       %in% installed.packages()) { install.packages("data.tree")       };
if(!"readxl"          %in% installed.packages()) { install.packages("readxl")          };
library("collapsibleTree")
library("readxl")
library("data.tree")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

Assessment decision tree for tool selection based on answer types. Select the item type you want to use and find out what kind of assessment application to use.

```{r, echo=FALSE}
# Read .xlsx file
assessment.tree <- read_excel("assessment_tree.xlsx")

# Create tree
collapsibleTree(assessment.tree,
                root      = "Question Type",        # Specify root name. This can be any string
                hierarchy = names(assessment.tree), # Use column headers from .xlsx file as branches
                width     = 800,                    # Set width in pixels
                fontSize  = 14                      # Set font size
               )
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

